name: Lint and Build

on:
  pull_request:
    branches: 
      - 'develop'
      - 'main'

jobs:
  build-project:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.9.0
      with:
        dotnet-version: 6.0.201
    - name: Build Project
      run: dotnet build IntroToCSharp/IntroToCSharp.csproj -warnaserror
    
    
