name: Deploy to Develop Repository

on:
  push:
    branches: 
      - develop

jobs:
  deploy-to-develop-repo:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Pushes to csharp-develop.captaincoder.org
      uses: jcollard/github-action-push-to-another-repository@main
      env:
        SSH_DEPLOY_KEY: ${{ secrets.DEVELOP_SITE_SSH_DEPLOY_KEY }}
      with:
        source-directory: '.'
        target-directory: '.'
        destination-github-username: 'CaptainCoderOrg'
        destination-repository-name: 'IntroToCSharpSite-dev-deploy'
        target-branch: main
    
    
